language: ruby
rvm:
  - jruby-head
  - jruby-19mode
  - ruby-head
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - rbx-2.2.1
  - rbx-2.2.0
  - rbx-2.1.1

matrix:
  allow_failures:
    - rvm: rbx-2.2.1
    - rvm: rbx-2.2.0
    - rvm: rbx-2.1.1
